#!/bin/sh

FILES=`while read TPL FILE DEP ; do [ "$TPL" != "#" ] && echo $FILE ; done < pages_index.txt | sort | uniq | xargs echo`

echo "pages.c: pages_index.txt pages.h $FILES" > pages.dep
for FILE in pages_index.txt pages.h $FILES
do
	echo ""
	echo "$FILE:"
done >> pages.dep
