.TH oscam.cert 5
.SH NAME
\fBoscam.cert\fR - Issuer Public Keys (IPK) for OSCam
.SH SYNOPSIS
Issuer Public Keys (IPK)
.SH DESCRIPTIONS
.PP
\fBCAID\fP:\fBreserved\fP:\fBIPK\fP
.RS 3n
mapping between CAID and IPK/sessions keys in hex, currently for Cryptoworks only
.SH EXAMPLES
 0100:00000000:0102030405060708090A0B0C0D0E0F
.RE
.RE
.SH "SEE ALSO"
\fBlist_smargo\fR(1), \fBoscam\fR(1), \fBoscam.ac\fR(5), \fBoscam.cacheex\fR(5), \fBoscam.conf\fR(5), \fBoscam.dvbapi\fR(5), \fBoscam.guess\fR(5), \fBoscam.ird\fR(5), \fBoscam.provid\fR(5), \fBoscam.ratelimit\fR(5), \fBoscam.server\fR(5), \fBoscam.services\fR(5), \fBoscam.srvid\fR(5), \fBoscam.tiers\fR(5), \fBoscam.user\fR(5), \fBoscam.whitelist\fR(5)