.TH oscam.provid 5
.SH NAME
\fBoscam.provid\fR - provider table for OSCam
.SH SYNOPSIS
provider table
.SH DESCRIPTIONS
.PP
\fB<caid>\fP:\fB<provid>\fP|\fB<provider>\fP|\fB<satellite>\fP|\fB<language>\fP
.RS 3n
provider table
.RE
.SH EXAMPLES
 0100:012345|MyPay-TV|Astra 19E|German
.SH "SEE ALSO"
\fBlist_smargo\fR(1), \fBoscam\fR(1), \fBoscam.ac\fR(5), \fBoscam.cacheex\fR(5), \fBoscam.cert\fR(5), \fBoscam.conf\fR(5), \fBoscam.dvbapi\fR(5), \fBoscam.guess\fR(5), \fBoscam.ird\fR(5), \fBoscam.ratelimit\fR(5), \fBoscam.server\fR(5), \fBoscam.services\fR(5), \fBoscam.srvid\fR(5), \fBoscam.tiers\fR(5), \fBoscam.user\fR(5), \fBoscam.whitelist\fR(5)
